# Generated by Django 6.0.7 on 2026-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_resume_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
